### ISSUE TITLE
README docs need Mac OSX instructions

### ISSUE THREAD

**Issue by mikeputnam** [dhmncivichacks/timewebsite#3]

**Comment by mathewpeterson** [comment]
What are your thoughts on Dockerizing all the things?

**Comment by bobwaldron** [comment]
Don't know enough about Docker to give useful feedback. If doing that will make your job easier, go for it. Can't do Docker on my old Dell (32 bit), but that's probably not a big issue. Looks like I could do Docker on my new Acer 64 bit Win 7 laptop.

**Comment by mikeputnam** [comment]
@mathewpeterson The only constraint I can think of regarding Docker, is that if we want to host the site on say Google (Container Engine) the pricing is tied to the number of nodes (1 512MB ram node is ~$5/mo) Given zero budget, we'd want to pile everything into a single node.

Otherwise, a pull request that introduces docker + instructions while preserving the existing non-docker instructions for those who prefer to author locally with virtualenv would be cool.

**Comment by chrisjaure** [comment]
I ended up not using Docker for the BarCampGB website, but I'm starting to wish I did, or at least used Google's other services instead of putting everything in the same node.

I could set up the necessary Docker stuff if @mathewpeterson hasn't already.

**Comment by mikeputnam** [comment]
Closed with #25 since switching to docker removed a lot of setup steps.
