### ISSUE TITLE
README docs need more specificity under the Linux/Ubuntu docs

### ISSUE THREAD

**Issue by mikeputnam** [dhmncivichacks/timewebsite#4]

**Comment by zo0o0ot** [comment]
Any specificity in particular that you're looking for here?  I noticed a big commit, but no URL yet.  Is this designed to run local at this point?  I'm not 100% of the timewebsite goal, or the intended output.  It seems like a nodeschool-type exercise, but I wanted to verify.

**Comment by mikeputnam** [comment]
Hey Ross!  Thanks for chiming in.

This web site is a combination learning/teaching effort + community directory of cool tech people and events.

This particular issue was me reminding myself (but certainly open to help) to add more details to the Linux setup a la the Windows setup. Assume experience level zero.

**Comment by zo0o0ot** [comment]
Fair enough, keep me posted.  If you need someone with a Linux box to try out your instructions.

**Comment by mikeputnam** [comment]
Closed with #25 since switching to docker removed a lot of setup steps.
