### ISSUE TITLE
README docs for Windows are untested on Windows :)

### ISSUE THREAD

**Issue by mikeputnam** [dhmncivichacks/timewebsite#5]

**Comment by bobwaldron** [comment]
The Windows README info is generally tested, per last night's install on my old Dell. In addition to the Python 3.5.1 link (Python on Windows), it would be good to add a download link, https://www.python.org/downloads/, which I'll do a pull request for (when I figure it out).

**Comment by mikeputnam** [comment]
Closed with #25 since switching to docker removed a lot of setup steps.
